"""Report generation service."""

from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.schemas.sessions import SessionSummary
from app.services.session import SessionService


class ReportService:
    """Service for generating and formatting reports."""

    def __init__(self, db: AsyncSession):
        self.db = db
        self.session_service = SessionService(db)

    async def generate_report(self, session_id: UUID) -> SessionSummary:
        """Generate a session report."""
        return await self.session_service.generate_summary(session_id)

    def to_markdown(self, summary: SessionSummary) -> str:
        """Convert summary to markdown format."""
        lines = [
            f"# Deposition Prep Session Report",
            f"",
            f"**Witness:** {summary.witness_name}",
            f"**Mode:** {summary.agent_mode.replace('_', ' ').title()}",
            f"**Duration:** {summary.duration_minutes} minutes",
            f"**Total Exchanges:** {summary.total_exchanges}",
            f"",
            f"---",
            f"",
            f"## Summary Statistics",
            f"",
            f"| Metric | Count |",
            f"|--------|-------|",
            f"| Facts Established | {summary.facts_established} |",
            f"| Contradictions Found | {summary.contradictions_found} |",
            f"| Unsupported Claims | {summary.unsupported_claims} |",
            f"",
            f"---",
            f"",
            f"## Key Facts Established",
            f"",
        ]

        for fact in summary.key_facts:
            lines.append(f"- {fact}")

        lines.extend([
            f"",
            f"---",
            f"",
            f"## Weak Spots (Requires Attention)",
            f"",
        ])

        for spot in summary.weak_spots:
            lines.append(f"- ⚠️ {spot}")

        lines.extend([
            f"",
            f"---",
            f"",
            f"## Likely Attack Vectors",
            f"",
        ])

        for vector in summary.attack_vectors:
            lines.append(f"- 🎯 {vector}")

        lines.extend([
            f"",
            f"---",
            f"",
            f"## Recommended Follow-ups",
            f"",
        ])

        for followup in summary.recommended_followups:
            lines.append(f"- [ ] {followup}")

        lines.extend([
            f"",
            f"---",
            f"",
            f"*Generated by Deposition Prep Simulator*",
        ])

        return "\n".join(lines)

    def to_plaintext(self, summary: SessionSummary) -> str:
        """Convert summary to plain text format."""
        lines = [
            f"DEPOSITION PREP SESSION REPORT",
            f"==============================",
            f"",
            f"Witness: {summary.witness_name}",
            f"Mode: {summary.agent_mode.replace('_', ' ').title()}",
            f"Duration: {summary.duration_minutes} minutes",
            f"Total Exchanges: {summary.total_exchanges}",
            f"",
            f"SUMMARY STATISTICS",
            f"------------------",
            f"Facts Established: {summary.facts_established}",
            f"Contradictions Found: {summary.contradictions_found}",
            f"Unsupported Claims: {summary.unsupported_claims}",
            f"",
            f"KEY FACTS ESTABLISHED",
            f"---------------------",
        ]

        for fact in summary.key_facts:
            lines.append(f"* {fact}")

        lines.extend([
            f"",
            f"WEAK SPOTS (REQUIRES ATTENTION)",
            f"--------------------------------",
        ])

        for spot in summary.weak_spots:
            lines.append(f"! {spot}")

        lines.extend([
            f"",
            f"LIKELY ATTACK VECTORS",
            f"---------------------",
        ])

        for vector in summary.attack_vectors:
            lines.append(f"> {vector}")

        lines.extend([
            f"",
            f"RECOMMENDED FOLLOW-UPS",
            f"----------------------",
        ])

        for followup in summary.recommended_followups:
            lines.append(f"[ ] {followup}")

        return "\n".join(lines)
